[#463] Create composer version of WaterfallHostBotDotNet
southworks/BotFramework-FunctionalTests pull request #105
Opened 2022-01-26 21:10 UTC by NahuelPerales

Addresses # 463

## Description
This PR adds a new project for the Waterfall Host Bot composer version.

### Detailed Changes
- Create **WaterfallHostBotComposer** project under _consumers/composer/_. 
- Adds all necessary files for integration with composer.
- Adds Bot controller for host interactions and dependency injection during runtime.
- Adds Skill controller for communication with other bots.
- Adds launch settings to run on port 35040 in local enviroment.
- Adds an app settings file for setting up skill bots.
- Updates bots dependencies to 4.15.0 version.

## Testing
These images show some of the processes working as expected on Emulator.

![image](https://user-images.githubusercontent.com/54330145/127702927-ff510551-e2d6-4a8e-801a-25f362c0cde0.png)

![image (33)](https://user-images.githubusercontent.com/54330145/127702207-5551fed1-9571-41a8-b28c-ce504b568dcc.png)

![image](https://user-images.githubusercontent.com/54330145/127702521-95529c25-f652-4918-bef8-a260b8008bfe.png)

![image](https://user-images.githubusercontent.com/54330145/127702636-0d870786-f47f-4c5a-9ce9-120169776ac3.png)

2022-01-27 13:42 UTC, sw-joelmut requested changes

2022-01-27 13:42 UTC, sw-joelmut commented on Bots/DotNet/Consumers/CodeFirst/WaterfallHostBot/appsettings.json
> +    },
This is not necessary, it's being addressed in this PR
https://github.com/southworks/BotFramework-FunctionalTests/pull/96/files#diff-24b95fd10b902a0b8bcb66524bd0f77f4118ee556392ed6a723e9d9bd250caf3R65-R70

2022-01-27 13:42 UTC, sw-joelmut commented on Bots/DotNet/Consumers/Composer/ComposerHostBotDotNet/.gitignore
> +generated/
Use the git ignore from [Bots\DotNet\Consumers\Composer\SimpleHostBotComposer\.gitignore](https://github.com/southworks/BotFramework-FunctionalTests/blob/d731d0767107c66e250a1974144bfe4ce988127e/Bots/DotNet/Consumers/Composer/SimpleHostBotComposer/.gitignore).
Before pushing this change, make sure to start the bot at least once, it should have generated some files under the generated folder like in [Bots\DotNet\Consumers\Composer\SimpleHostBotComposer\generated](https://github.com/southworks/BotFramework-FunctionalTests/tree/d731d0767107c66e250a1974144bfe4ce988127e/Bots/DotNet/Consumers/Composer/SimpleHostBotComposer/generated).

2022-01-27 13:42 UTC, sw-joelmut commented on Bots/DotNet/Consumers/Composer/ComposerHostBotDotNet/ComposerHostBotDotNet.botproj
> +{
Here are a few things to do.
- Make sure that all skills are here, i think the composer echo skill is missing, We also could add the waterfall composer skill, even if the PR isn't merged, but we ensure we don't have to do it after.
- You can use the [`Bots\DotNet\Consumers\Composer\SimpleHostBotComposer\SimpleHostBotComposer.botproj`](https://github.com/southworks/BotFramework-FunctionalTests/blob/f53af1eae65a1ecd6617c9ed41f93b8f283ea160/Bots/DotNet/Consumers/Composer/SimpleHostBotComposer/SimpleHostBotComposer.botproj) config to have similar changes, we should add the manifest and endpointName fields.

2022-01-27 13:42 UTC, sw-joelmut commented on Bots/DotNet/Consumers/Composer/ComposerHostBotDotNet/Nuget.config
> +<?xml version="1.0" encoding="utf-8"?>
Remove this file, make sure the bot compiles

2022-01-27 13:42 UTC, sw-joelmut commented on Bots/DotNet/Consumers/Composer/ComposerHostBotDotNet/settings/appsettings.json
> +      "endpointUrl": "http://localhost:35400/api/messages",
I think the only one missing is the Composer Echo

2022-01-27 13:42 UTC, sw-joelmut commented on Bots/DotNet/Consumers/Composer/ComposerHostBotDotNet/settings/appsettings.json
> +        "voiceFontName": "en-US-JennyNeural",
Use `en-US-AriaNeural` as it is in the simple composer bots

2022-01-27 13:42 UTC, sw-joelmut commented on Bots/DotNet/Consumers/Composer/ComposerHostBotDotNet/settings/appsettings.json
> +      },
I think we don't need AI.Orchestrator, remove it and make sure it works

2022-01-27 13:42 UTC, sw-joelmut commented on Bots/DotNet/Consumers/Composer/ComposerHostBotDotNet/ComposerHostBotDotNet.csproj
> +    <PackageReference Include="Microsoft.Bot.Builder.AI.Orchestrator" Version="4.15.0" />
I think we don't need AI.Orchestrator, remove it and make sure it works

2022-01-27 13:42 UTC, sw-joelmut commented on Bots/DotNet/FunctionalTestsBots.sln
> +VisualStudioVersion = 17.0.32112.339
I dont know if this could be a problem, we tend to leave it as is.

2022-01-27 13:42 UTC, sw-joelmut commented on Bots/DotNet/FunctionalTestsBots.sln
> +EndProject
WaterfallComposer doesn't exist anymore, it is the same bot as this one, remove it from the solution or else it fails at the start, after removing make sure it starts the solution without errors.
![imagen](https://user-images.githubusercontent.com/62260472/151369697-49502b63-2ab3-4079-ab14-c507156f6991.png)
![imagen](https://user-images.githubusercontent.com/62260472/151369859-4d32ac1e-4581-4f37-ac82-35c899fc3969.png)

2022-01-27 13:42 UTC, sw-joelmut commented on Bots/DotNet/Skills/CodeFirst/EchoSkillBot-v3/Web.config
> +<?xml version="1.0" encoding="utf-8"?>
This file should have not be changed in this PR

2022-01-27 13:42 UTC, sw-joelmut commented on Bots/DotNet/Skills/CodeFirst/WaterfallSkillBot/Dialogs/Sso/SsoSkillDialog.cs
> +using Microsoft.Bot.Connector.Authentication;
All these file changes, are already being address in the PR https://github.com/southworks/BotFramework-FunctionalTests/pull/96/files#diff-6e34c20106649b13cd3e3b9a03c7cd76f0c032061227dc0bff038d4ecff51177R65 for the WaterfallSkill

2022-01-28 14:31 UTC, sw-joelmut requested changes

2022-01-28 14:31 UTC, sw-joelmut commented on Bots/DotNet/Consumers/Composer/ComposerHostBotDotNet/settings/appsettings.json
> +      "endpointUrl": "http://localhost:35400/api/messages",
- Remove echoSkillBotDotNet21
- Remove EchoSkillBotComposer
- Move waterfallSkillBotDotNet, waterfallSkillBotJS, waterfallSkillBotPython below the echoSkillBotPython
- Add composerSkillBotDotNet below the waterfallSkillBotPython

2022-01-28 14:31 UTC, sw-joelmut commented on Bots/DotNet/Consumers/Composer/ComposerHostBotDotNet/ComposerHostBotDotNet.csproj
> +    <PackageReference Include="Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime" Version="4.15.0" />
Use the BotBuilderVersion variable declared in the Build.props file, you can use the other dotnet bots for reference

2022-01-28 15:18 UTC, sw-joelmut approved these changes

2022-01-28 18:53 UTC, JuanAr approved these changes
👍

2022-01-31 19:16 UTC, ceciliaavila requested changes

2022-01-31 19:16 UTC, ceciliaavila commented on Bots/DotNet/Consumers/Composer/ComposerHostBotDotNet/ComposerHostBotDotNet.botproj
> +	"echoSkillBotComposerDotNet": {
Check the indentation here.

2022-01-31 19:16 UTC, ceciliaavila commented on Bots/DotNet/Consumers/Composer/ComposerHostBotDotNet/ComposerHostBotDotNet.botproj
> +    "echoSkillBotDotNet21": {
DotNet21 bots no longer exist. I think we should remove this one.

2022-01-31 19:16 UTC, ceciliaavila commented on Bots/DotNet/Consumers/Composer/ComposerHostBotDotNet/README.md
> +
The readme was removed for the rest of the bots. We should remove this one as well.

2022-01-31 20:06 UTC, ceciliaavila approved these changes

2022-02-07 17:59 UTC, ceciliaavila commented
Promoted to MS in PR# 559

2022-02-07 17:59 UTC, closed without merging