[#463] Create composer version of WaterfallHostBotDotNet - Dialogs
southworks/BotFramework-FunctionalTests pull request #106
Opened 2022-01-26 21:44 UTC by NahuelPerales

Addresses # 463

## Description
This PR adds the dialogs for WaterfallHostBot Composer version.

### Detailed Changes
- Add **_Greeting_** message.
- Add the following bot dialogs with their respective functionality:
     - _MainDialog_
     - _SsoDialog_
     - _SsoSignInDialog_
- Add _**manifest.json**_ for the following skills:
     - _EchoSkillBotDotNet_
     - _EchoSkillBotDotNet21_
     - _EchoSkillBotDotNetV3_
     - _EchoSkillBotJS_
     - _EchoSkillBotJSV3_
     - _EchoSkillBotPython_
     - _WaterfallSkillBotDotNet_
     - _WaterfallSkillBotJS_
     - _WaterfallSkillBotPython_
     - _TeamsSkillBotDotNet_
     - _TeamsSkillBotJS_
     - _TeamsSkillBotPython_

## Testing
These images show some of the processes working as expected on Emulator.

![image](https://user-images.githubusercontent.com/54330145/127702927-ff510551-e2d6-4a8e-801a-25f362c0cde0.png)

![image (33)](https://user-images.githubusercontent.com/54330145/127702207-5551fed1-9571-41a8-b28c-ce504b568dcc.png)

![image](https://user-images.githubusercontent.com/54330145/127702521-95529c25-f652-4918-bef8-a260b8008bfe.png)

![image](https://user-images.githubusercontent.com/54330145/127702636-0d870786-f47f-4c5a-9ce9-120169776ac3.png)

2022-01-27 13:44 UTC, sw-joelmut requested changes
The PR description doesn't match what the PR has

2022-01-28 14:56 UTC, sw-joelmut approved these changes

2022-01-28 20:47 UTC, JuanAr approved these changes
👍

2022-01-31 20:11 UTC, ceciliaavila approved these changes

2022-02-07 18:03 UTC, ceciliaavila commented
Promoted to MS in PR# 560

2022-02-07 18:03 UTC, closed without merging