[#463] Create composer version of WaterfallHostBotDotNet - Test & Yamls
southworks/BotFramework-FunctionalTests pull request #107
Opened 2022-01-26 22:50 UTC by NahuelPerales

Fixes # 463

## Description
This PR updates the pipelines and test to cover the WaterfallHostBot Composer version.

### Detailed Changes
Pipelines:
- Updates deploy resources file to include the waterfall host bot.
- Updates the create app registrations  file to include the waterfall host bot.
- Updates the configure consumers file to include the waterfall host bot.
Tests:
- Updates CardActionsTests to cover the waterfall host bot.
- Updates FileUploadTests to cover the waterfall host bot.
- Updates MessageWithAttachmentTests to cover the waterfall host bot.
- Updates ProactiveTests to cover the waterfall host bot.
- Updates SignInTests to cover the waterfall host bot.

## Testing
![image](https://user-images.githubusercontent.com/54330145/129951502-bdde0cfb-a66c-40f9-a1d0-3cf54fd830b7.png)

![image](https://user-images.githubusercontent.com/54330145/129951668-2fcbd708-8f31-472d-afcc-c10093eb0d26.png)

2022-01-27 13:51 UTC, sw-joelmut requested changes
Add a Note at the start of the PR description like this PR (https://github.com/southworks/BotFramework-FunctionalTests/pull/96), this will let them know they have to create a new set of app registrations.
We could also mention the required variables to be set.

2022-01-27 18:50 UTC, sw-joelmut approved these changes
Just a minor thing, the new variables added put them below the note, so it is easier to know, connecting what the Note says

2022-01-31 20:15 UTC, ceciliaavila approved these changes

2022-02-07 18:06 UTC, ceciliaavila commented
Promoted to MS in PR# 561

2022-02-07 18:06 UTC, closed without merging