[#552][DotNet] Add CosmosDB Azure tests to the test solution
southworks/BotFramework-FunctionalTests pull request #110
Opened 2022-02-07 19:26 UTC by sw-joelmut

Addresses # 552

## Description
This PR adds the `CosmosDb` tests to the new `Integration` test project.

### Detailed Changes
- Added new `Integration.csproj` under the `Integration` folder and solution.
- Updated `Directory.build.props` to support the global `BotBuilderVersion` variable.
- Added two set of test classes, CosmosDbPartitionedStorage and CosmosDbStorage.
  - Added `CosmosDbAttribute` to share the database and container IDs to the `CosmosDb` fixture.
  - Added CosmosDbFxiture to perform common operations like reading the `appsettings.json`, creating the `CosmosDb` client to create and delete the database after all the tests passed, and to check if the `CosmosDb` server is up and running.
  - All test classes will perform CRUD operations over the database, alongside a few extra tests.

## Testing
The following image shows the new `CosmosDb` Integration tests working.
![image](https://user-images.githubusercontent.com/62260472/152990247-bfb09f61-d039-4832-8e92-dcd0f983f3dd.png)

2022-02-07 20:17 UTC, ceciliaavila requested changes

2022-02-07 20:17 UTC, ceciliaavila commented on Tests/Integration/DotNet/Azure/CosmosDb/CosmosDbPartitionedStorageTests.cs
> +    [Trait("TestCategory", "CosmosDb Partitioned")]
I think that if these TestCategories are no longer used, we should remove them.

2022-02-07 20:17 UTC, ceciliaavila commented on Tests/Integration/DotNet/Azure/CosmosDb/CosmosDbPartitionedStorageTests.cs
> +                Dialog CreateNestedDialog(int depth) => new ComponentDialog(nameof(ComponentDialog))
This function could be made static
```suggestion
                static Dialog CreateNestedDialog(int depth) => new ComponentDialog(nameof(ComponentDialog))
```

2022-02-07 20:17 UTC, ceciliaavila commented on Tests/Integration/DotNet/Azure/CosmosDb/CosmosDbStorageTests.cs
> +    [Trait("TestCategory", "CosmosDb")]
We can leave the Deprecated category as it could be useful in the future (v5 release), but the other two should be removed.

2022-02-08 12:50 UTC, sw-joelmut commented
@ceciliaavila feedback applied, thanks!

2022-02-08 12:59 UTC, ceciliaavila approved these changes

2022-02-09 13:13 UTC, sw-joelmut commented
Promoted `https://github.com/microsoft/BotFramework-FunctionalTests/pull/563`

2022-02-09 13:13 UTC, closed without merging