[#548] Update Skills tests' base structure
southworks/BotFramework-FunctionalTests pull request #133
Opened 2022-03-31 13:28 UTC by sw-joelmut

Addresses # 548

## Description
This PR refactors the `Skills` test structure, separating what needs to be in the `Common` folder, so `Standalone` bots can use the functionalities, additionally reduces duplicated functionality and separates the `CardActions` scenario into multiple classes to speed up the process.

### Detailed Changes
- Adds a new `TestCase` base class with common properties when building the test cases.
- Updates and moves the `TestCaseDataObject` to the Common folder.
- Updates the `ScriptTestBase` including the `Channels` list, since it's common across bots (Skills, Standalone).
- Updates all `CardActions` tests separating the scripts into its own test class, reducing the time it takes to execute this scenario locally or in the pipelines.
- Adds a new `CardTestBase` containing the base test and exclusions needed across `Cards'` test classes.
- Updates the Skill list from `Class` to an `Enum`, being consistent like its Host counterpart.
- Adds a new `SkillsTestCase` class containing all the lists (DeliveryModes, Hosts, Skills, etc) necessary to make the test cases combinations, as well as the `Cardinal Product` method to construct the test cases.
- Updated all tests to inherit from the `SkillsTestCase` class, reducing the amount of duplicated code required to make the test combinations.

## Testing
The following images show the Test Scenarios pipeline continue working as expected, and a sneak peek of how the new changes look compared to the previous version.
![imagen](https://user-images.githubusercontent.com/62260472/161064855-965fe50b-6b6b-4b6f-966b-a30e8c923a46.png)
![imagen](https://user-images.githubusercontent.com/62260472/161064875-3a4fe741-422a-4b15-99e2-5cdc1776cb00.png)

2022-04-04 14:24 UTC, ceciliaavila requested changes

2022-04-04 14:24 UTC, ceciliaavila commented on Tests/Functional/Skills/CardActions/CardBaseTests.cs
> +        }
This won't be needed if the PR enabling cards get merged first.

2022-04-04 14:24 UTC, ceciliaavila commented on Tests/Functional/Skills/Common/SkillBot.cs
> +        /// Echo UserAssignedMSI skill implemented using using DotNet 3.1.
```suggestion
        /// Echo UserAssignedMSI skill implemented using DotNet 3.1.
```

2022-04-04 14:24 UTC, ceciliaavila commented on Tests/Functional/Skills/Common/SkillBot.cs
> +        /// Echo MultiTenant skill implemented using using DotNet 3.1.
```suggestion
        /// Echo MultiTenant skill implemented using DotNet 3.1.
```

2022-04-04 14:24 UTC, ceciliaavila commented on Tests/Functional/Skills/Common/SkillBot.cs
> +        /// Echo SingleTenant skill implemented using using DotNet 3.1.
```suggestion
        /// Echo SingleTenant skill implemented using DotNet 3.1.
```

2022-04-04 14:24 UTC, ceciliaavila commented on Tests/Functional/Skills/Common/SkillBot.cs
> +        /// Echo MultiTenant v3 skill implemented using using DotNet 3.1.
The same in the rest of the comments.

2022-04-04 14:24 UTC, ceciliaavila commented on Tests/Functional/Skills/SignIn/SignInTests.cs
> +        public static bool Exclude(SkillsTestCase test) => test.Skill == SkillBot.ComposerSkillBotDotNet;
This won't be necessary if the PR enabling signIn gets merged first.

2022-04-05 19:23 UTC, sw-joelmut commented
@ceciliaavila fixed, thanks!

2022-04-05 19:25 UTC, ceciliaavila approved these changes

2022-04-22 20:08 UTC, sw-joelmut commented
/promoted 586

2022-04-22 20:08 UTC, closed without merging