[#548] Create Fn tests for supported authentication types - Update Javascript bots
southworks/BotFramework-FunctionalTests pull request #136
Opened 2022-04-01 20:09 UTC by ceciliaavila

Addresses # 548

## Description
This PR updates the JS bots to support SingleTenant and MSI authentication types.

### Detailed Changes
- Updated the following bots based on the implementation in the [skills samples](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_nodejs/81.skills-skilldialog):
   - SimpleHostBot
   - EchoSkillBot
   - WaterfallHostBot
   - WaterfallSkillBot
- Updated the SSO implementation in the Waterfall bots to work with CloudAdapter.

## Testing
Here we can see the Waterfall host and skill bots working with the three app types.
![image](https://user-images.githubusercontent.com/44245136/161333287-7f059f4c-2d8e-4093-bca0-64260e21e3e6.png)

2022-04-04 14:03 UTC, sw-joelmut requested changes

2022-04-04 14:03 UTC, sw-joelmut commented on Bots/JavaScript/WaterfallHostBot/index.js
> +const skillClient = botFrameworkAuthentication;
same here

2022-04-04 14:03 UTC, sw-joelmut commented on Bots/JavaScript/WaterfallSkillBot/index.js
> +const skillClient = botFrameworkAuthentication;
Shouldn't the `botFrameworkAuthentication.createBotFrameworkClient();` be executed here instead, inside the `ActivityRouterDialog`? Like the other bots?, otherwise this variable assignment could be removed and just pass `botFrameworkAuthentication`, remember to update the jsdoc parameter to match this type of variable.

2022-04-06 18:59 UTC, ceciliaavila commented on Bots/JavaScript/WaterfallHostBot/index.js
> +const skillClient = botFrameworkAuthentication;
Changes applied. Thanks!

2022-04-06 18:59 UTC, ceciliaavila commented on Bots/JavaScript/WaterfallSkillBot/index.js
> +const skillClient = botFrameworkAuthentication;
Changes applied and tested. Thanks!

2022-04-07 17:50 UTC, sw-joelmut approved these changes

2022-04-07 19:24 UTC, ceciliaavila commented
/promoted 577

2022-04-07 19:24 UTC, closed without merging