[#409] Update docs based on feedback - Make KeyVault creation optional
southworks/BotFramework-FunctionalTests pull request #24
Opened 2021-07-01 18:45 UTC by ceciliaavila

Addresses # 409

## Description
This PR updates the [01-Create Shared Resources](https://github.com/microsoft/BotFramework-FunctionalTests/blob/main/build/yaml/sharedResources/createSharedResources.yml) pipeline making the creation of the KeyVault and the AppRegistrations optional.
The **_KeyVaultObjectId_** variable is now optional and when it's set, the steps to create the keyVault and the AppRegistrations will be executed. If it's not set, or its value is blank, these steps will be skipped.

### Detailed Changes
- Merged the `Create_Key_Vault` and `Create_App_Registrations` stages into one stage.
- Added a job to evaluate the value of the _KeyVaultObjectId_ variable.
- Added a condition to the `Deploy_Key_Vault` job to run only if the _KeyVaultObjectId_ is set.

## Testing
These images show the pipeline running with and without the _KeyVaultObjectId_ variable.
![image](https://user-images.githubusercontent.com/44245136/124174418-b6a80380-da82-11eb-98f9-4c794670a55f.png)

2021-07-01 18:49 UTC, MartinLuccanera approved these changes

2021-07-01 18:49 UTC, sw-joelmut requested changes

2021-07-01 18:49 UTC, sw-joelmut commented on build/yaml/sharedResources/createSharedResources.yml
> +  # KeyVaultObjectId: (optional) Suscription's Object Id to create the keyvault to store App Registrations.
```suggestion
  # KeyVaultObjectId: (optional) Subscription's Object Id to create the keyvault to store App Registrations.
```

2021-07-01 18:52 UTC, santgr11 approved these changes

2021-07-01 18:53 UTC, GiulianoDolceTalianoSantoro approved these changes

2021-07-01 18:57 UTC, ceciliaavila commented on build/yaml/sharedResources/createSharedResources.yml
> +  # KeyVaultObjectId: (optional) Suscription's Object Id to create the keyvault to store App Registrations.
Nice catch! Thanks!

2021-07-01 20:50 UTC, sw-joelmut approved these changes

2021-07-02 14:37 UTC, ceciliaavila commented
Promoted to MS in PR# 446

2021-07-02 14:37 UTC, closed without merging