[#452] Add VNet integration and docker container documentation
southworks/BotFramework-FunctionalTests pull request #34
Opened 2021-07-08 19:24 UTC by santgr11

Fixes # 452

# Summary

This PR adds new documents with information on the Virtual Network and how to set up a docker container integrated with the bots. Also updates existing readmes with the added variables for these integrations.

## Specific changes

- Add `regionalVirtualNetworkIntegration.md`  document with information on the regional virtual network integration.
- Add `setupDockerContainer.md` document with steps to use a custom docker container with the bots.
- Update `README.md` with links to the new documents.
- Update `pipelines.md` adding the variables introduced with the VNet and containers integration.

2021-07-08 19:49 UTC, MartinLuccanera approved these changes

2021-07-12 12:37 UTC, GiulianoDolceTalianoSantoro approved these changes

2021-07-12 13:14 UTC, ceciliaavila requested changes

2021-07-12 13:14 UTC, ceciliaavila commented on Docs/pipelines.md
> +| **ContainerRegistryName** | User | (optional) Pricing tier for the Web App resources. |
I think this description is wrong.

2021-07-12 13:23 UTC, santgr11 commented on Docs/pipelines.md
> +| **ContainerRegistryName** | User | (optional) Pricing tier for the Web App resources. |
fixed, ty

2021-07-12 13:25 UTC, ceciliaavila approved these changes

2021-07-12 15:13 UTC, santgr11 commented
Promoted to MS PR464

2021-07-12 15:13 UTC, closed without merging